version: '3'
services:
  php:
    image: serg0cloud/php-fpm_8.2.6_mssql_mysql
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql
    networks:
      internal:
        ipv4_address: 172.20.0.3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/log:/var/log/nginx'
    depends_on:
      - php
      - mysql
    networks:
      - internal

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pagination
      - MYSQL_ROOT_PASSWORD=rootroot
    volumes:
      - './db:/var/lib/mysql'
      - './mysql:/etc/mysql/conf.d'
    networks:
      internal:
        ipv4_address: 172.20.0.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    environment:
        PMA_HOST: mysql
    volumes:
      - /sessions
    networks:
      - internal

networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/16
